version: "3.4"

services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env

    api:
        build: ./
        volumes:
            - .:/api
        env_file:
            - .env
        ports:
            - 8000:8000
        command: bash -c "sleep 10 && python3 manage.py migrate && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db

volumes:
    pgdata: