version: "3.4"

services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env

    api:
        build: ./
        volumes:
            - .:/api
        env_file: 
            - .env
        ports:
            - 8000:8000
        command: bash ./run.sh
        depends_on:
            - db

volumes:
    pgdata: