version: "3.4"

services:
    db:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_HOST: $POSTGRES_HOST
            POSTGRES_PORT: $POSTGRES_PORT

    api:
        build: ./
        volumes:
            - .:/api
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_HOST: $POSTGRES_HOST
            POSTGRES_PORT: $POSTGRES_PORT
            ADMIN_USER: $ADMIN_USER
            ADMIN_EMAIL: $ADMIN_EMAIL
            ADMIN_PASS: $ADMIN_PASS
            DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
            COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
        ports:
            - 8000:8000
        command: bash ./test.sh
        depends_on:
            - db

volumes:
    pgdata: